FROM openjdk:8
RUN apt-get update
RUN apt-get install -y netcat jq telnet curl

ENV SCALA_VERSION 2.13.0
ENV SBT_VERSION 1.6.2

RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
RUN apt-get update
RUN apt-get install sbt

WORKDIR /app
ADD . /app
RUN sbt assembly
CMD ["/bin/bash","-c", "chmod +x /app/consumer-start.sh && /app/consumer-start.sh"]